### ISSUE TITLE
Favourite page not working.

### ISSUE THREAD

**Issue by NAKULgupta23** [namanbansal102/SCM-FINAL-PROJECT-TEAM-20#13] opened 2024-05-09 10:11 UTC
Hi team,

I've encountered an issue with the favorite page functionality. It seems that it's not working correctly at the moment. I've tested it thoroughly, and it's consistently failing to perform as expected. I'll dive deeper into the code to pinpoint the exact issue, but I wanted to bring it to your attention as soon as possible.

Looking forward to resolving this and getting the favorite page back on track!

Best regards,
NAKUL GUPTA

**Comment by lovisharora7860** [comment] 2024-05-14 16:40
The issue is resolved by our team.

**Closed by lovisharora7860** 2024-05-14 16:40 UTC
